### 🔗 Links and Resources
- [select()](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.DataFrame.select.html)
- [col()](https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/api/pyspark.sql.functions.col.html)

📌 Reading data into a Spark DataFrame

In [0]:
import os
if not os.getenv("DATABRICKS_RUNTIME_VERSION"):
    from spark_setup import spark

In [0]:
df = spark.read.table("population_metrics.default.countries_population")

df.toPandas()

     COUNTRY_ID  ... SUB_REGION_ID
0           210  ...          30.0
1           211  ...          40.0
2           212  ...          10.0
3           213  ...         120.0
4           214  ...         120.0
..          ...  ...           ...
244         205  ...         160.0
245         206  ...          10.0
246         207  ...          60.0
247         208  ...         160.0
248         209  ...          70.0

[249 rows x 10 columns]

📌 Using select() with String Column Names

In [4]:
df.select("COUNTRY_ID", "NAME", "POPULATION").toPandas()

     COUNTRY_ID                                          NAME  POPULATION
0           210                                     Sri Lanka    21323733
1           211                                         Sudan    42813238
2           212                                      Suriname      581372
3           213                        Svalbard and Jan Mayen        2667
4           214                                        Sweden    10036379
..          ...                                           ...         ...
244         205                                  South Africa    58558270
245         206  South Georgia and the South Sandwich Islands          30
246         207                     South Korea (Republic of)    51225308
247         208                                   South Sudan    11062113
248         209                                         Spain    46736776

[249 rows x 3 columns]